/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvButton {
        /**
          * @default 'solid'
         */
        "appearance": 'solid' | 'outline' | 'danger' | 'tertiary' | 'link';
        /**
          * @default ''
         */
        "ariaLabel": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default false
         */
        "iconOnly": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'ghost';
        /**
          * @default 'v1'
         */
        "version": 'v1' | 'v2';
    }
}
export interface IvButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIvButtonElement;
}
declare global {
    interface HTMLIvButtonElementEventMap {
        "ivClick": { version: 'v1' | 'v2' };
    }
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLIvButtonElementEventMap>(type: K, listener: (this: HTMLIvButtonElement, ev: IvButtonCustomEvent<HTMLIvButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLElementTagNameMap {
        "iv-button": HTMLIvButtonElement;
    }
}
declare namespace LocalJSX {
    interface IvButton {
        /**
          * @default 'solid'
         */
        "appearance"?: 'solid' | 'outline' | 'danger' | 'tertiary' | 'link';
        /**
          * @default ''
         */
        "ariaLabel"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * @default false
         */
        "iconOnly"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        "onIvClick"?: (event: IvButtonCustomEvent<{ version: 'v1' | 'v2' }>) => void;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'ghost';
        /**
          * @default 'v1'
         */
        "version"?: 'v1' | 'v2';
    }

    interface IvButtonAttributes {
        "version": 'v1' | 'v2';
        "variant": 'primary' | 'ghost';
        "appearance": 'solid' | 'outline' | 'danger' | 'tertiary' | 'link';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "loading": boolean;
        "fullWidth": boolean;
        "iconOnly": boolean;
        "ariaLabel": string;
    }

    interface IntrinsicElements {
        "iv-button": Omit<IvButton, keyof IvButtonAttributes> & { [K in keyof IvButton & keyof IvButtonAttributes]?: IvButton[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `attr:${K}`]?: IvButtonAttributes[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `prop:${K}`]?: IvButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-button": LocalJSX.IntrinsicElements["iv-button"] & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
        }
    }
}
