/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvInput {
        /**
          * @default ''
         */
        "helperText": string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default 'default'
         */
        "state": 'default' | 'error' | 'success';
        /**
          * @default 'v1'
         */
        "version": 'v1' | 'v2';
    }
}
declare global {
    interface HTMLIvInputElement extends Components.IvInput, HTMLStencilElement {
    }
    var HTMLIvInputElement: {
        prototype: HTMLIvInputElement;
        new (): HTMLIvInputElement;
    };
    interface HTMLElementTagNameMap {
        "iv-input": HTMLIvInputElement;
    }
}
declare namespace LocalJSX {
    interface IvInput {
        /**
          * @default ''
         */
        "helperText"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default 'default'
         */
        "state"?: 'default' | 'error' | 'success';
        /**
          * @default 'v1'
         */
        "version"?: 'v1' | 'v2';
    }

    interface IvInputAttributes {
        "version": 'v1' | 'v2';
        "placeholder": string;
        "label": string;
        "helperText": string;
        "state": 'default' | 'error' | 'success';
    }

    interface IntrinsicElements {
        "iv-input": Omit<IvInput, keyof IvInputAttributes> & { [K in keyof IvInput & keyof IvInputAttributes]?: IvInput[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `attr:${K}`]?: IvInputAttributes[K] } & { [K in keyof IvInput & keyof IvInputAttributes as `prop:${K}`]?: IvInput[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-input": LocalJSX.IntrinsicElements["iv-input"] & JSXBase.HTMLAttributes<HTMLIvInputElement>;
        }
    }
}
