/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IvButton {
        /**
          * @default 'solid'
         */
        "appearance": 'solid' | 'outline' | 'danger';
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'ghost';
        /**
          * @default 'v1'
         */
        "version": 'v1' | 'v2';
    }
}
declare global {
    interface HTMLIvButtonElement extends Components.IvButton, HTMLStencilElement {
    }
    var HTMLIvButtonElement: {
        prototype: HTMLIvButtonElement;
        new (): HTMLIvButtonElement;
    };
    interface HTMLElementTagNameMap {
        "iv-button": HTMLIvButtonElement;
    }
}
declare namespace LocalJSX {
    interface IvButton {
        /**
          * @default 'solid'
         */
        "appearance"?: 'solid' | 'outline' | 'danger';
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'ghost';
        /**
          * @default 'v1'
         */
        "version"?: 'v1' | 'v2';
    }

    interface IvButtonAttributes {
        "version": 'v1' | 'v2';
        "variant": 'primary' | 'ghost';
        "appearance": 'solid' | 'outline' | 'danger';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
    }

    interface IntrinsicElements {
        "iv-button": Omit<IvButton, keyof IvButtonAttributes> & { [K in keyof IvButton & keyof IvButtonAttributes]?: IvButton[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `attr:${K}`]?: IvButtonAttributes[K] } & { [K in keyof IvButton & keyof IvButtonAttributes as `prop:${K}`]?: IvButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iv-button": LocalJSX.IntrinsicElements["iv-button"] & JSXBase.HTMLAttributes<HTMLIvButtonElement>;
        }
    }
}
